# Please add the routes for your module here
campaignchain_channel_xing_create:
    path: /channel/xing/create
    defaults: { _controller: CampaignChainChannelXingBundle:Xing:create }
    
campaignchain_channel_xing_login:
    path:  /channel/xing/create/login
    defaults: { _controller: CampaignChainChannelXingBundle:Xing:login }